### ISSUE TITLE
Improve error message when the `publish` directory is invalid

### ISSUE THREAD

**Issue by ehmicky** [edm00se/netlify-plugin-gridsome-cache#2]
This issue is the same as what was reported on the upstream repository: https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues/33

The upstream repository fixed it in https://github.com/jlengstorf/netlify-plugin-gatsby-cache/pull/34

A common error seems to be for users that forgot to set a `publish` directory. Providing a better error message would be good in those cases.

**Comment by edm00se** [comment]
I'm sorry I didn't see this sooner. I'll see about getting the relevant changes incorporated.

**Comment by edm00se** [comment]
Closed by 6478edd. The package has been updated to `1.0.3` and [published to npm](https://www.npmjs.com/package/netlify-plugin-gridsome-cache), which should make it ready to go.

Thanks for reporting @ehmicky!

**Comment by ehmicky** [comment]
Thanks @edm00se!
Would it be possible to upgrade its version [in the `netlify/plugins` repository](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#update-a-plugin) as well? This will make the update available in the Netlify UI as well. Thanks!

**Comment by edm00se** [comment]
Absolutely! I did feel like something was missing from my checklist. The PR is opened here: netlify/plugins#121
